config/routes.rb
Swa::Application.routes.draw do
  

  

  

  resources :people do
    resources :skills
    resources :services
    resources :pics
    resources :products
  end
  
  resources :services do
    resources :pics
  end
  
  resources :products do
    resources :pics
  end
  
  resources :pics
  
  devise_for :users, 
              :path => "/", 
              :path_names => {
                                    :sign_in => 'login',
                                    :sign_out => 'logout'
                              }

  root :to => 'base#start'

end

app/models/service.rb
class Service < ActiveRecord::Base
  
  belongs_to :person
  
  has_many :pics, :as => :owner
  
  attr_accessible :certificate, :experience, :hardware, :level, :name, :price, :software, :person_id
  
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  
  before_filter :get_person
  
  # GET /services
  # GET /services.json
  def index
    @services = Service.all
    @that_action = "resources"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @services }
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/new
  # GET /services/new.json
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to @person ? [@person, @service.class] : @service, notice: 'Service was successfully created.' }
        format.json { render json: @service, status: :created, location: @service }
      else
        format.html { render action: "new" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.json
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to @person ? [@person, @service.class] : @service, notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end
  
  
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for [@person,@service] do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table class="form">
    <tr>
        <th><%= f.label :name %></th>
        <td><%= f.text_field :name %></td>
    </tr>
    <tr>
        <th><%= f.label :level, "Niveau" %></th>
        <td><%= f.text_field :level %></td>
    </tr>
    <tr>
        <th><%= f.label :experience, "Erfahrung" %></th>
        <td><%= f.text_field :experience %></td>
    </tr>
    <tr>
        <th><%= f.label :certificate, "Zertifikate" %></th>
        <td><%= f.text_field :certificate %></td>
    </tr>
    <tr>
        <th><%= f.label :software %></th>
        <td><%= f.text_field :software %></td>
    </tr>
    <tr>
        <th><%= f.label :hardware %></th>
        <td><%= f.text_field :hardware %></td>
    </tr>
    <tr>
        <th><%= f.label :price %></th>
        <td><%= f.text_field :price %></td>
    </tr>
  </table>
  <%= f.hidden_field :person_id, :value => @person.id %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<%= render 'form' %>

app/views/services/index.html.erb
<%= render "shared/user_nav", :person => @person %>

    <div class="container_24">
    
        <div class="grid_6">
            <%= render "shared/resource_nav", :navon => "service" %>
        </div>
    
        <div class="grid_18">
        
            <% @person.services.each do |srv| %>
                <div class="market_box">
                    <div class="box_header">
                        <%= srv.name %>
                        <%= link_to "+ Bild", new_service_pic_path(srv), :class => "dialog right button", :title => "Bild-Upload" %>
                        <%= link_to "edit", edit_person_service_path(@person, srv), :class => "dialog right button", :title => "Skill '#{srv.name}' bearbeiten" %>
                    </div>
                    <div class="half_box">
                        <table class="market">
                            <% if srv.level && !srv.level.blank? %>
                            <tr>
                                <th>Niveau</th>
                                <td><%= srv.level %></td>
                            </tr>
                            <% end %>
                            <% if srv.experience && !srv.experience.blank? %>
                            <tr>
                                <th>Erfahrung</th>
                                <td><%= srv.experience %></td>
                            </tr>
                            <% end %>
                            <% if srv.certificate && !srv.certificate.blank? %>
                            <tr>
                                <th>Zertifikate</th>
                                <td><%= srv.certificate %></td>
                            </tr>
                            <% end %>
                            <% if srv.software && !srv.software.blank? %>
                            <tr>
                                <th>Software</th>
                                <td><%= srv.software %></td>
                            </tr>
                            <% end %>
                            <% if srv.hardware && !srv.hardware.blank? %>
                            <tr>
                                <th>Hardware</th>
                                <td><%= srv.hardware %></td>
                            </tr>
                            <% end %>
                            <% if srv.price && !srv.price.blank? && srv.price != 0 %>
                            <tr>
                                <th>Preis</th>
                                <td>ab <strong><%= number_to_currency srv.price %></strong> €/h</td>
                            </tr>
                            <% end %>
                        </table>
                    </div>
                    <div class="half_box image_holder">
                        <% srv.pics.each do |pic| %>
                            <%= image_tag pic.image.thumb('338x180#').url() %>
                        <% end %>
                    </div>
                    <div class="clearfix"></div>
                </div>
            <% end %>
        
        </div>
        <div class="clearfix"></div>
    
    </div>

app/views/services/new.html.erb
<%= render 'form' %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @service.name %>
</p>

<p>
  <b>Level:</b>
  <%= @service.level %>
</p>

<p>
  <b>Experience:</b>
  <%= @service.experience %>
</p>

<p>
  <b>Certificate:</b>
  <%= @service.certificate %>
</p>

<p>
  <b>Software:</b>
  <%= @service.software %>
</p>

<p>
  <b>Hardware:</b>
  <%= @service.hardware %>
</p>

<p>
  <b>Price:</b>
  <%= @service.price %>
</p>




<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>