config/routes.rb
Swa::Application.routes.draw do
  

  

  

  resources :people do
    resources :skills
    resources :services
    resources :pics
    resources :products
  end
  
  resources :services do
    resources :pics
  end
  
  resources :products do
    resources :pics
  end
  
  resources :pics
  
  devise_for :users, 
              :path => "/", 
              :path_names => {
                                    :sign_in => 'login',
                                    :sign_out => 'logout'
                              }

  root :to => 'base#start'

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  
  belongs_to :person
  attr_accessible :certificate, :experience, :image_uid, :language, :level, :name, :panorama_crop, :scare_crop, :software, :hardware, :image, :person_id
  
  image_accessor :image
  validates_property  :mime_type, :of => :image, :in => %w(image/jpeg image/png image/gif)
  
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  
  before_filter :get_person
  
  def index
    @skills = Skill.all
    @that_action = "skills"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skills }
    end
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    @skill = Skill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/new
  # GET /skills/new.json
  def new
    @skill = Skill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/1/edit
  def edit
    @skill = Skill.find(params[:id])
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(params[:skill])

    respond_to do |format|
      if @skill.save
        if @skill.person
          format.html { redirect_to [@skill.person, @skill.class], notice: 'Skill was successfully created.' }
        else
          format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        end
        format.json { render json: @skill, status: :created, location: @skill }
      else
        format.html { render action: "new" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /skills/1
  # PUT /skills/1.json
  def update
    @skill = Skill.find(params[:id])

    respond_to do |format|
      if @skill.update_attributes(params[:skill])
        if @skill.person
          format.html { redirect_to [@skill.person, @skill.class], notice: 'Skill was successfully updated.' }
        else
          format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        end
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy

    respond_to do |format|
      format.html { redirect_to skills_url }
      format.json { head :no_content }
    end
  end
  
  
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= form_for [@person,@skill] do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table class="form">
    <tr>
        <th><%= f.label :name %></th>
        <td><%= f.text_field :name %></td>
    </tr>
    <tr>
        <th><%= f.label :level, "Niveau" %></th>
        <td><%= f.text_field :level %></td>
    </tr>
    <tr>
        <th><%= f.label :experience, "Erfahrung" %></th>
        <td><%= f.text_field :experience %></td>
    </tr>
    <tr>
        <th><%= f.label :certificate, "Zertifikate" %></th>
        <td><%= f.text_field :certificate %></td>
    </tr>
    <tr>
        <th><%= f.label :software %></th>
        <td><%= f.text_field :software %></td>
    </tr>
    <tr>
        <th><%= f.label :hardware %></th>
        <td><%= f.text_field :hardware %></td>
    </tr>
    <tr>
        <th><%= f.label :image_uid %></th>
        <td><%= f.file_field :image %></td>
    </tr>
  </table>
  <%= f.hidden_field :person_id, :value => @person.id %>
<!--
  <div class="field">
    <%#= f.label :language %><br />
    <%#= f.text_field :language %>
  </div>
-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<%= render 'form' %>

app/views/skills/index.html.erb
<% if @person %>
    <%= render "shared/user_nav", :person => @person %>

    <div class="container_24">
    
        <div class="grid_6">
            <ul id="aside_nav">
                <li><%= link_to "Ausbildung", '#', :class => "aktiv" %></li>
                <li><%= link_to "Software", '#'%></li>
                <li><%= link_to "Hardware", '#'%></li>
                <li><%= link_to "Sprachen", '#'%></li>
                <li><%= link_to "Sonstiges", '#'%></li>
                <li><%= link_to "New Skill", new_person_skill_path(@person), :class => "dialog", :title => "Neuen Skill anlegen" %></li>
            </ul>
        </div>
    
        <div class="grid_18">
        
            <% @person.skills.each do |skill| %>
                <div class="market_box">
                    <div class="box_header">
                        <%= skill.name %>
                        <%= link_to "edit", edit_person_skill_path(@person, skill), :class => "dialog right button", :title => "Skill '#{skill.name}' bearbeiten" %>
                    </div>
                    <div class="half_box">
                        <table class="market">
                            <% if skill.level && !skill.level.blank? %>
                            <tr>
                                <th>Niveau</th>
                                <td><%= skill.level %></td>
                            </tr>
                            <% end %>
                            <% if skill.experience && !skill.experience.blank? %>
                            <tr>
                                <th>Erfahrung</th>
                                <td><%= skill.experience %></td>
                            </tr>
                            <% end %>
                            <% if skill.certificate && !skill.certificate.blank? %>
                            <tr>
                                <th>Zertifikate</th>
                                <td><%= skill.certificate %></td>
                            </tr>
                            <% end %>
                            <% if skill.software && !skill.software.blank? %>
                            <tr>
                                <th>Software</th>
                                <td><%= skill.software %></td>
                            </tr>
                            <% end %>
                            <% if skill.hardware && !skill.hardware.blank? %>
                            <tr>
                                <th>Hardware</th>
                                <td><%= skill.hardware %></td>
                            </tr>
                            <% end %>
                        </table>
                    </div>
                    <div class="half_box">
                        <%= image_tag skill.image.thumb('338x180#').url() if skill.image %>
                    </div>
                    <div class="clearfix"></div>
                </div>
            <% end %>
        
        </div>
        <div class="clearfix"></div>
    
    </div>
<% else %>
    <h1>Listing skills</h1>

    <table>
      <tr>
        <th>Name</th>
        <th>Language</th>
        <th>Software</th>
        <th>Certificate</th>
        <th>Experience</th>
        <th>Level</th>
        <th>Scare crop</th>
        <th>Panorama crop</th>
        <th>Image uid</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.name %></td>
        <td><%= skill.language %></td>
        <td><%= skill.software %></td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= skill.scare_crop %></td>
        <td><%= skill.panorama_crop %></td>
        <td><%= skill.image_uid %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>

    <br />

    <%= link_to 'New Skill', new_skill_path %>
<% end %>

app/views/skills/new.html.erb
<%= render 'form' %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:  <%= @skill.name %>
</p>

<p>
  <b>Language:</b>
  <%= @skill.language %>
</p>

<p>
  <b>Software:</b>
  <%= @skill.software %>
</p>

<p>
  <b>Certificate:</b>
  <%= @skill.certificate %>
</p>

<p>
  <b>Experience:</b>
  <%= @skill.experience %>
</p>

<p>
  <b>Level:</b>
  <%= @skill.level %>
</p>

<p>
  <b>Scare crop:</b>
  <%= @skill.scare_crop %>
</p>

<p>
  <b>Panorama crop:</b>
  <%= @skill.panorama_crop %>
</p>

<p>
  <b>Image uid:</b>
  <%= image_tag @skill.image.url() %>
</p>


<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>