config/routes.rb
Swa::Application.routes.draw do
  

  

  

  resources :people do
    resources :skills
    resources :services
    resources :pics
    resources :products
  end
  
  resources :services do
    resources :pics
  end
  
  resources :products do
    resources :pics
  end
  
  resources :pics
  
  devise_for :users, 
              :path => "/", 
              :path_names => {
                                    :sign_in => 'login',
                                    :sign_out => 'logout'
                              }

  root :to => 'base#start'

end

app/views/shared/_resource_nav.html.erb
<% navon ||= "service" %>
<% that_pathes = { "service" => new_person_service_path(@person), "products" => new_person_product_path(@person) } %>
<% that_titles = { "service" => "Neue Leistung anlegen", "products" => "Neues Produkt anlegen" } %>

<ul id="aside_nav">
    <li><%= link_to "Leistungen", person_services_path(@person), :class => "#{'aktiv' if navon == "service"}" %></li>
    <li><%= link_to "Produkte", person_products_path(@person), :class => "#{'aktiv' if navon == "products"}" %></li>
<!--    <li><%#= link_to "Objekte", '#', :class => "#{'aktiv' if navon == "objects"}" %></li> -->
    <li><%= link_to that_titles[navon], that_pathes[navon], :class => "dialog", :title => that_titles[navon] %></li>
</ul>

app/views/shared/_user_nav.html.erb
<% person ||= current_person %>
<div class="container_24">
    <div class="grid_24">
        <div id="magic_nav">
            
            <div id="user_pic">
                <% if person.id == 1 %>
                    <%= image_tag "torsten_30.png", :width => 30, :height => 30 %>
                <% elsif person.id == 2 %>
                    <%= image_tag "marco_30.png", :width => 30, :height => 30 %>
                <% end %>
            </div>
            
            <div id="user_info">
                <span class="name"><%= person.full_name %></span>
                <span class="proffession"><%= person.proffession %></span>
            </div>
            
            <ul id="user_navigation">
                <li><%= link_to 'Informationen', person_path(person), :class => "workz #{'aktiv' if @that_action && @that_action == 'info'}" %></li>
                <li><%= link_to 'Skills', person_skills_path(person), :class => "workz #{'aktiv' if @that_action && @that_action == 'skills'}" %></li>
                <li><%= link_to 'Resourcen', person_services_path(person), :class => "workz #{'aktiv' if @that_action && @that_action == 'resources'}" %></li>
                <li><%= link_to 'Portfolio', '#', :class => "#{'aktiv' if @that_action && @that_action == 'portfolio'}" %></li>
                <li><%= link_to 'Kontakte', '#', :class => "#{'aktiv' if @that_action && @that_action == 'contacts'}" %></li>
                <li><%= link_to 'Bewertungen', '#', :class => "#{'aktiv' if @that_action && @that_action == 'xxx'}" %></li>
            </ul>
            
            <div class="clearfix"></div>
        </div>
    </div>
</div>  