config/routes.rb
Swa::Application.routes.draw do
  

  

  

  resources :people do
    resources :skills
    resources :services
    resources :pics
    resources :products
  end
  
  resources :services do
    resources :pics
  end
  
  resources :products do
    resources :pics
  end
  
  resources :pics
  
  devise_for :users, 
              :path => "/", 
              :path_names => {
                                    :sign_in => 'login',
                                    :sign_out => 'logout'
                              }

  root :to => 'base#start'

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  belongs_to :person
  
  has_many :pics, :as => :owner
  
  attr_accessible :name, :data, :manufactor, :requirements, :product_type, :usecase, :person_id
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_filter :get_person
  
  def index
    @products = Product.all
    @that_action = "resources"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new( 
                                  :name => params[:product][:name], 
                                  :manufactor => params[:product][:manufactor],
                                  :requirements => params[:product][:requirements],
                                  :usecase => params[:product][:usecase],
                                  :product_type => params[:product][:product_type],
                                  :person_id => params[:product][:person_id]
                          )
    @product.save
    @product.data = params[:product][:data]
    
    respond_to do |format|
      if @product.save
        format.html { redirect_to @person ? [@person, @product.class] : @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @person ? [@person, @product.class] : @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for [@person, @product] do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table class="form" id="products_form_table">
      <tbody>
    <tr>
        <th><%= f.label :name %></th>
        <td colspan="2"><%= f.text_field :name %></td>
    </tr>
    <tr>
        <th><%= f.label :manufactor %></th>
        <td colspan="2"><%= f.text_field :manufactor %></td>
    </tr>
    <tr>
        <th><%= f.label :product_type %></th>
        <td colspan="2"><%= f.text_field :product_type %></td>
    </tr>
    <tr>
        <th><%= f.label :usecase %></th>
        <td colspan="2"><%= f.text_field :usecase %></td>
    </tr>
    <tr>
        <th><%= f.label :requirements %></th>
        <td colspan="2"><%= f.text_field :requirements %></td>
    </tr>
    <%= f.fields_for :data, @product.data do |d| %>
        <% @product.data.try(:each) do |key, value| %>
            <tr>
                <th><%= text_field_tag key, key, :class => 'text_field dynamicAttributeName' %></th>
                <td><%= d.text_field key, :class => 'text_field', :value => value %></td>
                <td><a href='#' class='btn removeRow'>X</a></td>
            </tr>
        <% end %>
    <%- end -%>
    </tbody>
  </table>
  <%= f.hidden_field :person_id, :value => @person.id %>


<table class="hidden muster_feld">
    <tr>
        <th><input class='text_field dynamicAttributeName' id='' name='' placeholder='Neues Attribut' size='30' type='text' /></th>
        <td class="data_value"><input class='text_field' id='bar' name='' placeholder='value' size='30'  type='text'  /></td>
        <td><a href='#' class='btn removeRow'>X</a></td>
    </tr>
</table>

<%= link_to 'Neue Eigenschaft anlegen', '#', :class => 'button addAttribute btn-primary' %>
<div class="clearfix"></div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<script type='text/javascript'>

    $("#products_form_table").on("keyup", '.dynamicAttributeName',  function(event){
        nameElem  = $(this);
        valueElem = nameElem.closest('tr').children('.data_value').children('.text_field');
        value     = nameElem.val().toLowerCase();
        valueElem.attr('id',          'product_data_' + value       );
        valueElem.attr('name',        'product[data][' + value + ']');
        valueElem.attr('placeholder', 'value for ' + value          );
    });

    $('.attributeContainer').delegate('.removeRow', 'click', function(){
        $(this).closest('tr').html('');
    });

    $('.addAttribute').on('click', function(){
        $("#products_form_table").append( $('.muster_feld').html() );
        console.log("clicked")
    });
</script>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<%= render "shared/user_nav", :person => @person %>

    <div class="container_24">
    
        <div class="grid_6">
            <%= render "shared/resource_nav", :navon => "products" %>
        </div>
    
        <div class="grid_18">
        
            <% @person.products.each do |pdt| %>
                <div class="market_box">
                    <div class="box_header">
                        <%= pdt.name %>
                        <%= link_to "+ Bild", new_product_pic_path(pdt), :class => "dialog right button", :title => "Bild-Upload" %>
                        <%= link_to "edit", edit_person_product_path(@person, pdt), :class => "dialog right button", :title => "Skill '#{pdt.name}' bearbeiten" %>
                    </div>
                    <div class="half_box">
                        <table class="market">
                            <% if pdt.manufactor && !pdt.manufactor.blank? %>
                            <tr>
                                <th>Hersteller</th>
                                <td><%= pdt.manufactor %></td>
                            </tr>
                            <% end %>
                            <% if pdt.product_type && !pdt.product_type.blank? %>
                            <tr>
                                <th>Typ</th>
                                <td><%= pdt.product_type %></td>
                            </tr>
                            <% end %>
                            <% if pdt.usecase && !pdt.usecase.blank? %>
                            <tr>
                                <th>Anwendungen</th>
                                <td><%= pdt.usecase %></td>
                            </tr>
                            <% end %>
                            <% if pdt.requirements && !pdt.requirements.blank? %>
                            <tr>
                                <th>Vorraussetzungen</th>
                                <td><%= pdt.requirements %></td>
                            </tr>
                            <% end %>
                            <% pdt.data.try(:each) do |k,v| %>
                                <tr>
                                    <th><%= k.titleize %></th>
                                    <td><%= v %></td>
                                </tr>
                            <% end %>
                        </table>
                    </div>
                    <div class="half_box image_holder">
                        <% pdt.pics.each do |pic| %>
                            <%= image_tag pic.image.thumb('338x180#').url() %>
                        <% end %>
                    </div>
                    <div class="clearfix"></div>
                </div>
            <% end %>
        
        </div>
        <div class="clearfix"></div>
    
    </div>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Manufactor:</b>
  <%= @product.manufactor %>
</p>

<p>
  <b>Type:</b>
  <%= @product.product_type %>
</p>

<p>
  <b>Usecase:</b>
  <%= @product.usecase %>
</p>

<p>
  <b>Requirements:</b>
  <%= @product.requirements %>
</p>

<p>
  <b>Data:</b>
  <% @product.data.try(:each) do |k,v| %>
    <%= k %>: <%= v %><br/>
  <% end %>
  <%= @product.data %>
</p>


<% @product.data.try(:each) do |key, value| %>
    <div class='row'>
      <p class='span3'>
        <%= key %>
      </p>
      <p class='span3'><%= value %></p>
    </div>
  <%- end -%>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>